version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    command: gunicorn soccer_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/soccer_app/static
    expose:
      - 8000
    env_file: .env
  
  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/app/soccer_app/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
