version: "3.8"

services:
  web:
    image: "${WEB_IMAGE}"
    command: gunicorn soccer_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/soccer_app/static
    ports:
      - 8000:8000
    env_file: .env
  
  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/app/soccer_app/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
