# Generated by Django 4.1.5 on 2023-01-13 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Auto created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Auto updated at')),
                ('name', models.CharField(max_length=200, verbose_name='Team name')),
                ('city', models.CharField(max_length=200, verbose_name='City name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
